/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useEffect, useMemo, useState } from "react";
import { useSiteContent } from "@/components/providers/SiteContentProvider";
import { ManagedImage } from "@/components/ui/ManagedImage";
import { getPublicVehicleBrands,getPublicVehicleModels,getPublicVehicleTypes,searchPublicVehicleCompatibilities,VEHICLE_TYPES,type VehicleBrand,type VehicleCompatibilityFull,type VehicleModel } from "@/lib/supabase/vehicle-compatibility";
import type { Product } from "@/lib/site-data";import { whatsappUrl } from "@/lib/whatsapp";
type Mode="vehicle"|"connector"|"unknown";

function CompatibleProducts({products,connectors}:{products:Product[];connectors:string[]}){const normalized=new Set(connectors.map(x=>x.trim().toLowerCase()));const matches=products.filter(p=>p.active&&p.connectorType&&normalized.has(p.connectorType.trim().toLowerCase()));if(!matches.length)return <p className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-zinc-400">Todavía no tenemos productos cargados para estos conectores. Consultanos por WhatsApp.</p>;return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{matches.map(p=><a key={p.id} href={p.href} className="group flex flex-col overflow-hidden rounded-2xl border border-white/10 bg-white/3"><div className="flex h-40 items-center justify-center bg-zinc-950/60 p-3"><ManagedImage source={p.image} alt={p.name} className="max-h-full max-w-full object-contain transition group-hover:scale-105"/></div><div className="p-4"><h3 className="text-lg font-black uppercase text-white">{p.name}</h3><p className="mt-1 line-clamp-2 text-sm text-zinc-400">{p.description}</p><span className="mt-3 inline-block text-xs font-bold uppercase text-red-400">Ver producto →</span></div></a>)}</div>}
function connectorsFor(row:VehicleCompatibilityFull){return Array.from(new Set([row.connectorLow,row.combinedHighLow?null:row.connectorHigh,row.connectorFog,row.connectorAux].filter((x):x is string=>Boolean(x))))}
function range(row:VehicleCompatibilityFull){return row.yearTo?`${row.yearFrom}–${row.yearTo}`:`Desde ${row.yearFrom}`}

export function VehicleFinder(){const{content}=useSiteContent();const[mode,setMode]=useState<Mode>("vehicle"),[types,setTypes]=useState<string[]>([...VEHICLE_TYPES]),[type,setType]=useState(""),[brands,setBrands]=useState<VehicleBrand[]>([]),[brand,setBrand]=useState(""),[models,setModels]=useState<VehicleModel[]>([]),[model,setModel]=useState(""),[year,setYear]=useState(""),[results,setResults]=useState<VehicleCompatibilityFull[]|null>(null),[searching,setSearching]=useState(false),[connector,setConnector]=useState(""),[connectorSearch,setConnectorSearch]=useState("");
 useEffect(()=>{getPublicVehicleTypes().then(x=>x?.length&&setTypes(x))},[]);useEffect(()=>{setBrand("");setModel("");setBrands([]);setModels([]);setResults(null);if(type)getPublicVehicleBrands(type).then(x=>setBrands(x||[]))},[type]);useEffect(()=>{setModel("");setModels([]);setResults(null);if(brand)getPublicVehicleModels(brand,type).then(x=>setModels(x||[]))},[brand,type]);
 async function search(){if(!type)return;setSearching(true);const rows=await searchPublicVehicleCompatibilities(type,brand||undefined,model||undefined);const y=year?Number(year):null;setResults((rows||[]).filter(r=>y===null||(y>=r.yearFrom&&(r.yearTo===null||y<=r.yearTo))));setSearching(false)}
 const allConnectors=useMemo(()=>Array.from(new Set((results||[]).flatMap(connectorsFor))),[results]);const wa=whatsappUrl("Hola DCL Cree LED, no encuentro mi vehículo/conector en la web. ¿Me ayudan a elegir el LED correcto?");const tabs:[Mode,string][]=[["vehicle","Conozco mi vehículo"],["connector","Conozco el conector"],["unknown","No sé qué conector uso"]];
 return <div className="space-y-6"><div className="flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setMode(id)} className={mode===id?"rounded-full border border-red-500/60 bg-red-600/15 px-4 py-2 text-xs font-bold uppercase text-red-200":"rounded-full border border-white/10 px-4 py-2 text-xs font-bold uppercase text-zinc-300"}>{label}</button>)}</div>
 {mode==="vehicle"&&<div className="rounded-[1.75rem] border border-white/10 bg-zinc-950/60 p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Select label="Tipo" value={type} onChange={setType} options={types.map(x=>[x,x])}/><Select label="Marca (opcional)" value={brand} onChange={setBrand} disabled={!type} options={brands.map(x=>[x.id,x.name])}/><Select label="Modelo (opcional)" value={model} onChange={setModel} disabled={!brand} options={models.map(x=>[x.id,x.name])}/><label className="text-sm text-zinc-300"><span className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-zinc-400">Año (opcional)</span><input type="number" value={year} onChange={e=>setYear(e.target.value)} placeholder="2020" className="w-full rounded-xl border border-white/10 bg-zinc-900 px-3 py-2.5 text-white"/></label></div><button type="button" disabled={!type||searching} onClick={search} className="mt-4 rounded-full bg-red-600 px-7 py-3 text-xs font-bold uppercase text-white disabled:opacity-40">{searching?"Buscando...":"Buscar"}</button>
 {results&&<div className="mt-6 space-y-5"><div><h3 className="text-lg font-black uppercase text-white">Compatibilidades encontradas</h3><p className="text-sm text-zinc-400">{results.length} variante(s). Podés completar más campos y volver a buscar para refinar.</p></div>{results.map(r=><article key={r.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><b className="text-white">{r.vehicleType} · {r.brandName} {r.modelName}</b><p className="mt-1 text-sm text-zinc-400">{range(r)}{r.version?` · ${r.version}`:""}</p><div className="mt-2 flex flex-wrap gap-2 text-xs">{r.combinedHighLow&&<Tag text={`Alta y baja: ${r.connectorLow}`}/>} {!r.combinedHighLow&&r.connectorLow&&<Tag text={`Baja: ${r.connectorLow}`}/>} {!r.combinedHighLow&&r.connectorHigh&&<Tag text={`Alta: ${r.connectorHigh}`}/>} {r.connectorFog&&<Tag text={`Antiniebla: ${r.connectorFog}`}/>} {r.connectorAux&&<Tag text={`Auxiliar: ${r.connectorAux}`}/>}</div></article>)}{results.length?<><h3 className="text-lg font-black uppercase text-white">Productos compatibles</h3><CompatibleProducts products={content.products} connectors={allConnectors}/></>:<p className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-zinc-300">No encontramos coincidencias con esos datos. Podés quitar filtros o consultarnos por WhatsApp.</p>}</div>}</div>}
 {mode==="connector"&&<div className="rounded-[1.75rem] border border-white/10 bg-zinc-950/60 p-5"><div className="flex gap-3"><input value={connector} onChange={e=>setConnector(e.target.value)} placeholder="H1, H4, H7..." className="w-full max-w-xs rounded-xl bg-zinc-900 p-3"/><button onClick={()=>setConnectorSearch(connector.trim())} className="rounded-full bg-red-600 px-6 text-xs font-bold uppercase">Buscar</button></div>{connectorSearch&&<div className="mt-6"><CompatibleProducts products={content.products} connectors={[connectorSearch]}/></div>}</div>}
 {mode==="unknown"&&<div className="rounded-[1.75rem] border border-white/10 bg-zinc-950/60 p-8 text-center"><p className="font-black uppercase">¿No sabés qué lámpara usa?</p><a href={wa} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-full bg-red-600 px-6 py-3 text-sm font-bold uppercase">Consultanos por WhatsApp</a></div>}</div>}
function Select({label,value,onChange,options,disabled}:{label:string;value:string;onChange:(v:string)=>void;options:string[][];disabled?:boolean}){return <label className="text-sm text-zinc-300"><span className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-zinc-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} className="w-full rounded-xl border border-white/10 bg-zinc-900 px-3 py-2.5 text-white disabled:opacity-40"><option value="">Cualquiera</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Tag({text}:{text:string}){return <span className="rounded-full bg-red-600/15 px-3 py-1 text-red-200">{text}</span>}
