import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { createAdminServerClient, isServiceRoleConfigured } from "@/lib/supabase/server";

const productColumns = "id,name,price,stock,active,category,connector_type,chip_type,voltage,watts,lumens";
const salesColumns = "id,customer_id,customer_vehicle_id,status,notes,subtotal,total,created_at,payment_method";
const customerColumns = "id,full_name,phone,email,notes,created_at,updated_at";
const vehicleColumns = "id,customer_id,vehicle_model_id,brand_name,model_name,year,plate,notes,created_at,updated_at";
const mapCustomer = (r: any) => ({ id: r.id, fullName: r.full_name, phone: r.phone || undefined, email: r.email || undefined, notes: r.notes || undefined, createdAt: r.created_at });
const mapVehicle = (r: any) => ({ id: r.id, customerId: r.customer_id, brandName: r.brand_name, modelName: r.model_name, year: r.year || undefined, plate: r.plate || undefined, notes: r.notes || undefined });
const mapProduct = (r: any) => ({ id: r.id, name: r.name, price: Number(r.price), stock: r.stock, active: r.active, category: r.category || undefined, connectorType: r.connector_type || undefined, chipType: r.chip_type || undefined, voltage: r.voltage || undefined, watts: r.watts || undefined, lumens: r.lumens || undefined });
async function guard() { if (!(await isAdminAuthenticated())) return NextResponse.json({ ok: false, message: "No autorizado." }, { status: 401 }); if (!isServiceRoleConfigured()) return NextResponse.json({ ok: false, error: "Falta configurar SUPABASE_SERVICE_ROLE_KEY para administrar ventas." }, { status: 500 }); return null; }

async function customerHistory(customerId: string) {
  const db = createAdminServerClient(); const { data: c, error: ce } = await db.from("customers").select(customerColumns).eq("id", customerId).maybeSingle(); if (ce) throw new Error(ce.message); if (!c) return null;
  const [{ data: vehicles, error: ve }, { data: sales, error: se }] = await Promise.all([db.from("customer_vehicles").select(vehicleColumns).eq("customer_id", customerId).order("created_at", { ascending: false }), db.from("sales").select(salesColumns).eq("customer_id", customerId).order("created_at", { ascending: false })]); if (ve || se) throw new Error(ve?.message || se?.message);
  const saleIds = (sales || []).map((s: any) => s.id); const { data: items, error: ie } = saleIds.length ? await db.from("sale_items").select("id,sale_id,product_id,product_name,quantity,unit_price,unit_cost,line_total,created_at").in("sale_id", saleIds) : { data: [], error: null }; if (ie) throw new Error(ie.message);
  const itemIds = (items || []).map((i: any) => i.id);
  const [{ data: installations, error: ine }, { data: warranties, error: we }] = await Promise.all([saleIds.length ? db.from("installations").select("id,sale_id,status").in("sale_id", saleIds) : Promise.resolve({ data: [], error: null }), itemIds.length ? db.from("warranties").select("id,sale_item_id,status").in("sale_item_id", itemIds) : Promise.resolve({ data: [], error: null })]); if (ine || we) throw new Error(ine?.message || we?.message);
  const warrantyIds = (warranties || []).map((w: any) => w.id); const { data: claims, error: cle } = warrantyIds.length ? await db.from("warranty_claims").select("id,warranty_id,status,description").in("warranty_id", warrantyIds) : { data: [], error: null }; if (cle) throw new Error(cle.message);
  const vehiclesById = new Map((vehicles || []).map((v: any) => [v.id, mapVehicle(v)])); const itemsBySale = new Map<string, any[]>(); for (const i of items || []) itemsBySale.set((i as any).sale_id, [...(itemsBySale.get((i as any).sale_id) || []), { id: (i as any).id, productId: (i as any).product_id, productName: (i as any).product_name, quantity: (i as any).quantity, unitPrice: Number((i as any).unit_price), unitCost: (i as any).unit_cost == null ? undefined : Number((i as any).unit_cost), lineTotal: Number((i as any).line_total) }]);
  const installationBySale = new Map((installations || []).map((i: any) => [i.id ? i.sale_id : "", i]));
  const claimsByWarranty = new Map<string, any[]>(); for (const claim of claims || []) claimsByWarranty.set((claim as any).warranty_id, [...(claimsByWarranty.get((claim as any).warranty_id) || []), { id: (claim as any).id, status: (claim as any).status, description: (claim as any).description }]);
  return { customer: mapCustomer(c), vehicles: (vehicles || []).map(mapVehicle), sales: (sales || []).map((s: any) => ({ id: s.id, status: s.status, total: Number(s.total), notes: s.notes || undefined, paymentMethod: s.payment_method || undefined, createdAt: s.created_at, vehicle: s.customer_vehicle_id ? vehiclesById.get(s.customer_vehicle_id) : undefined, items: itemsBySale.get(s.id) || [], installation: installationBySale.has(s.id) ? { id: installationBySale.get(s.id).id, status: installationBySale.get(s.id).status } : undefined, warranties: (warranties || []).filter((w: any) => (itemsBySale.get(s.id) || []).some(i => i.id === w.sale_item_id)).map((w: any) => ({ id: w.id, status: w.status, saleItemId: w.sale_item_id, claims: claimsByWarranty.get(w.id) || [] })) })) };
}
async function summary() { const db = createAdminServerClient(); const start = new Date(); start.setHours(0, 0, 0, 0); const iso = start.toISOString(); const [{ data: sales, error: se }, { count, error: ce }] = await Promise.all([db.from("sales").select("id,total").eq("status", "completed").gte("created_at", iso), db.from("customers").select("id", { count: "exact", head: true }).gte("created_at", iso)]); if (se || ce) throw new Error(se?.message || ce?.message); const ids = (sales || []).map((s: any) => s.id); const { data: items, error: ie } = ids.length ? await db.from("sale_items").select("quantity").in("sale_id", ids) : { data: [], error: null }; if (ie) throw new Error(ie.message); return { total: (sales || []).reduce((n: number, s: any) => n + Number(s.total), 0), operations: sales?.length || 0, products: (items || []).reduce((n: number, i: any) => n + i.quantity, 0), newCustomers: count || 0 }; }

export async function GET(request: Request) { const blocked = await guard(); if (blocked) return blocked; try { const p = new URL(request.url).searchParams; const db = createAdminServerClient();
  if (p.get("customerId")) { const data = await customerHistory(p.get("customerId")!); return data ? NextResponse.json({ ok: true, data }) : NextResponse.json({ ok: false, message: "Cliente no encontrado." }, { status: 404 }); }
  if (p.has("customerQuery")) { const q = p.get("customerQuery")?.trim() || ""; let req = db.from("customers").select(customerColumns).order("full_name").limit(12); if (q) req = req.or(`full_name.ilike.%${q}%,phone.ilike.%${q}%`); const { data, error } = await req; if (error) throw new Error(error.message); return NextResponse.json({ ok: true, data: (data || []).map(mapCustomer) }); }
  if (p.has("productQuery")) { const q = p.get("productQuery")!.trim().toLowerCase(); const { data, error } = await db.from("products").select(productColumns).eq("active", true).order("name").limit(250); if (error) throw new Error(error.message); const matches = (data || []).filter((row: any) => [row.name, row.category, row.connector_type, row.chip_type, row.voltage, row.watts, row.lumens].some(value => String(value ?? "").toLowerCase().includes(q))).sort((a: any,b: any) => Number(b.name.toLowerCase().startsWith(q)) - Number(a.name.toLowerCase().startsWith(q))).slice(0, 10); return NextResponse.json({ ok: true, data: matches.map(mapProduct) }); }
  if (p.has("history")) { let req = db.from("sales").select(salesColumns).order("created_at", { ascending: false }).limit(100); const period = p.get("period"); if (period !== "all") { const d = new Date(); if (period === "today") d.setHours(0,0,0,0); else if (period === "week") d.setDate(d.getDate() - 7); else d.setMonth(d.getMonth() - 1); req = req.gte("created_at", d.toISOString()); } const { data: rows, error } = await req; if (error) throw new Error(error.message); const saleIds = (rows || []).map((r: any) => r.id); const customerIds = [...new Set((rows || []).map((r: any) => r.customer_id))]; const [{ data: customers }, { data: vehicles }, { data: items }] = await Promise.all([customerIds.length ? db.from("customers").select(customerColumns).in("id", customerIds) : Promise.resolve({ data: [] }), db.from("customer_vehicles").select(vehicleColumns), saleIds.length ? db.from("sale_items").select("sale_id,quantity").in("sale_id", saleIds) : Promise.resolve({ data: [] })]); const cById = new Map((customers || []).map((c: any) => [c.id, mapCustomer(c)])); const vById = new Map((vehicles || []).map((v: any) => [v.id, mapVehicle(v)])); const countBySale = new Map<string,number>(); for (const i of items || []) countBySale.set((i as any).sale_id, (countBySale.get((i as any).sale_id)||0)+(i as any).quantity); const needle=(p.get("query")||"").toLowerCase(); const data=(rows||[]).map((r:any)=>({id:r.id,createdAt:r.created_at,status:r.status,total:Number(r.total),paymentMethod:r.payment_method||undefined,customer:cById.get(r.customer_id),vehicle:r.customer_vehicle_id?vById.get(r.customer_vehicle_id):undefined,itemCount:countBySale.get(r.id)||0})).filter((r:any)=>!needle||r.id.toLowerCase().includes(needle)||r.customer?.fullName.toLowerCase().includes(needle)||r.customer?.phone?.toLowerCase().includes(needle)); return NextResponse.json({ok:true,data}); }
  if (p.get("saleId")) { const { data: sale, error } = await db.from("sales").select(salesColumns).eq("id", p.get("saleId")!).maybeSingle(); if (error || !sale) return NextResponse.json({ ok:false, message:"Venta no encontrada." }, {status:404}); const h = await customerHistory((sale as any).customer_id); const base = h?.sales.find((s: any) => s.id === (sale as any).id); const { data: movements } = await db.from("inventory_movements").select("id,product_id,quantity_delta,reason,created_at").eq("reference_type", "sale").eq("reference_id", (sale as any).id); return NextResponse.json({ok:true,data:{...base,customer:h?.customer,inventoryMovements:(movements||[]).map((m:any)=>({id:m.id,productId:m.product_id,quantityDelta:m.quantity_delta,reason:m.reason,createdAt:m.created_at}))}}); }
  const [{ data: customers, error }, quickSummary] = await Promise.all([db.from("customers").select(customerColumns).order("full_name").limit(12), summary()]); if (error) throw new Error(error.message); return NextResponse.json({ ok:true, data:{customers:(customers||[]).map(mapCustomer),summary:quickSummary} });
} catch (e) { return NextResponse.json({ok:false,error:e instanceof Error?e.message:"No se pudo cargar Ventas."},{status:500}); } }

export async function POST(request: Request) { const blocked = await guard(); if (blocked) return blocked; try { const body = await request.json() as Record<string, unknown>; const db=createAdminServerClient(); if (body.action === "create_customer") { const fullName=String(body.fullName||"").trim(); if (!fullName) return NextResponse.json({ok:false,message:"El nombre es obligatorio."},{status:400}); const {data,error}=await db.from("customers").insert({full_name:fullName,phone:String(body.phone||"").trim()||null,email:String(body.email||"").trim()||null,notes:String(body.notes||"").trim()} as never).select(customerColumns).single(); if(error) throw new Error(error.message); return NextResponse.json({ok:true,data:mapCustomer(data)}); }
 if (body.action === "create_vehicle") { const customerId=String(body.customerId||"").trim(), brandName=String(body.brandName||"").trim(), modelName=String(body.modelName||"").trim(); const year=body.year?Number(body.year):null; if(!customerId||!brandName||!modelName||(year!==null&&(!Number.isInteger(year)||year<1886))) return NextResponse.json({ok:false,message:"Cliente, marca y modelo son obligatorios; el año debe ser válido."},{status:400}); const {data,error}=await db.from("customer_vehicles").insert({customer_id:customerId,brand_name:brandName,model_name:modelName,year,plate:String(body.plate||"").trim()||null,notes:String(body.notes||"").trim()} as never).select(vehicleColumns).single();if(error)throw new Error(error.message);return NextResponse.json({ok:true,data:mapVehicle(data)}); }
 if (body.action === "create_sale") { const customerId=String(body.customerId||"").trim(), items=Array.isArray(body.items)?body.items:[], payment=String(body.paymentMethod||""); if(!customerId||!items.length||!Object.hasOwn({cash:1,transfer:1,mercadopago:1,debit:1,credit:1,other:1},payment))return NextResponse.json({ok:false,message:"Seleccioná cliente, productos y una forma de pago válida."},{status:400}); const {data,error}=await db.rpc("create_sale_with_inventory",{p_customer_id:customerId,p_customer_vehicle_id:String(body.customerVehicleId||"").trim()||null,p_notes:String(body.notes||"").trim(),p_items:items,p_create_installation:Boolean(body.createInstallation),p_payment_method:payment,p_idempotency_key:String(body.idempotencyKey||"").trim()} as never); if(error||!data)throw new Error(error?.message||"No se pudo registrar la venta.");return NextResponse.json({ok:true,data:{saleId:data}}); }
 return NextResponse.json({ok:false,message:"Acción de ventas inválida."},{status:400}); } catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:"No se pudo guardar la información."},{status:500});} }
