import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { apiError,apiInternalError,boundedString,isUuid,readJsonObject } from "@/lib/api";
import { rateLimit } from "@/lib/rate-limit";
import { createAdminServerClient,isServiceRoleConfigured } from "@/lib/supabase/server";
async function guard(){if(!(await isAdminAuthenticated()))return apiError("UNAUTHORIZED","No autorizado.",401);if(!isServiceRoleConfigured())return apiError("CONFIGURATION_ERROR","Administración no configurada.",503);return null}
export async function GET(){const blocked=await guard();if(blocked)return blocked;try{const{data,error}=await createAdminServerClient().from("work_gallery").select("*").order("sort_order").limit(100);if(error)throw error;return NextResponse.json({ok:true,data})}catch(e){return apiInternalError("admin_gallery_list",e)}}
export async function POST(request:Request){const limited=rateLimit(request,"admin-gallery",{limit:30,windowMs:10*60*1000});if(limited)return limited;const blocked=await guard();if(blocked)return blocked;const body=await readJsonObject(request);if(!body)return apiError("BAD_REQUEST","Datos inválidos.",400);const imageUrl=boundedString(body.imageUrl,2000,{required:true}),title=boundedString(body.title,120),caption=boundedString(body.caption,280),itemType=boundedString(body.itemType,20)||"installation",sortOrder=Number(body.sortOrder||0);if(!imageUrl||!['delivery','installation','customer','other'].includes(itemType)||!Number.isInteger(sortOrder))return apiError("BAD_REQUEST","Revisá la imagen y sus datos.",400);try{const{data,error}=await createAdminServerClient().from("work_gallery").insert({image_url:imageUrl,title:title||null,caption:caption||null,item_type:itemType,active:body.active!==false,sort_order:sortOrder} as never).select("*").single();if(error)throw error;return NextResponse.json({ok:true,data})}catch(e){return apiInternalError("admin_gallery_create",e)}}
export async function PATCH(request:Request){const blocked=await guard();if(blocked)return blocked;const body=await readJsonObject(request);if(!body||!isUuid(body.id))return apiError("BAD_REQUEST","Elemento inválido.",400);const row={title:boundedString(body.title,120)||null,caption:boundedString(body.caption,280)||null,item_type:boundedString(body.itemType,20)||"installation",active:Boolean(body.active),sort_order:Number(body.sortOrder||0)};try{const{error}=await createAdminServerClient().from("work_gallery").update(row as never).eq("id",body.id);if(error)throw error;return NextResponse.json({ok:true})}catch(e){return apiInternalError("admin_gallery_update",e)}}
export async function DELETE(request:Request){const blocked=await guard();if(blocked)return blocked;const body=await readJsonObject(request);if(!body||!isUuid(body.id))return apiError("BAD_REQUEST","Elemento inválido.",400);try{const{error}=await createAdminServerClient().from("work_gallery").delete().eq("id",body.id);if(error)throw error;return NextResponse.json({ok:true})}catch(e){return apiInternalError("admin_gallery_delete",e)}}
