"use client";
import { useState } from "react";
import { useSiteContent } from "@/components/providers/SiteContentProvider";
import { DEFAULT_THEME, themePresets, type ThemePreset } from "@/lib/theme";
import { upsertSupabaseSiteSettings } from "@/lib/supabase/site-settings";

export function AppearanceSettings() {
  const { content, setContent } = useSiteContent();
  const [applied, setApplied] = useState<ThemePreset>(content.siteSettings.themePreset || DEFAULT_THEME);
  const [status, setStatus] = useState("");
  const selected = content.siteSettings.themePreset || DEFAULT_THEME;
  const preview = (themePreset: ThemePreset) => setContent((previous) => ({ ...previous, siteSettings: { ...previous.siteSettings, themePreset } }));
  async function apply() { setStatus("Guardando paleta…"); const result = await upsertSupabaseSiteSettings({ ...content.siteSettings, themePreset: selected }); if (!result.success) return setStatus(result.error || "No se pudo guardar la paleta."); setApplied(selected); setStatus("Paleta aplicada."); }
  return <section className="rounded-[1.75rem] border border-white/10 bg-zinc-950/80 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Apariencia</h2><p className="mt-2 text-sm text-zinc-400">Elegí una paleta. La estructura, tipografía y composición permanecen iguales.</p></div><span className="rounded-full bg-red-600/15 px-3 py-1 text-xs font-bold text-red-300">Activa: {themePresets.find((theme) => theme.id === applied)?.name}</span></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{themePresets.map((theme) => <button type="button" key={theme.id} onClick={() => preview(theme.id)} className={`rounded-2xl border p-4 text-left transition ${selected === theme.id ? "border-red-500 bg-red-600/10" : "border-white/10 hover:border-red-500/40"}`}><div className="overflow-hidden rounded-xl border border-white/10" style={{ backgroundColor: theme.swatches[0], color: theme.id === "clean-light" ? "#172033" : "#fff" }}><div className="flex items-center justify-between border-b border-black/10 px-3 py-2 text-[9px] font-bold"><span>DCL</span><span>PRODUCTOS · VENTAS</span></div><div className="grid grid-cols-[.8fr_1fr] gap-2 p-3"><div className="min-h-16 rounded-lg" style={{ backgroundColor: theme.swatches[1] }}/><div><b className="block text-sm">Título destacado</b><small className="block opacity-70">Métrica o producto</small><span className="mt-2 inline-block rounded px-2 py-1 text-[9px] font-bold" style={{ backgroundColor: theme.swatches[1] }}>ACCIONAR</span></div></div></div><b className="mt-4 block">{theme.name}</b><small className="mt-1 block text-zinc-400">{theme.description}</small>{selected === theme.id && <small className="mt-3 block font-bold text-red-300">Vista previa activa</small>}</button>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" onClick={() => void apply()} className="rounded-full bg-red-600 px-5 py-3 text-xs font-bold uppercase">Aplicar paleta</button><button type="button" onClick={() => preview(applied)} className="rounded-full border border-white/15 px-5 py-3 text-xs font-bold uppercase">Restaurar tema activo</button>{status && <p className="text-sm text-zinc-400">{status}</p>}</div></section>;
}
