/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element */
"use client";
import { useEffect,useState } from "react";
type Row={id:string;image_url:string;title:string|null;caption:string|null;item_type:string;active:boolean;sort_order:number};
export function GalleryManager(){const[rows,setRows]=useState<Row[]>([]),[draft,setDraft]=useState({imageUrl:"",title:"",caption:"",itemType:"installation",sortOrder:0}),[uploading,setUploading]=useState(false),[error,setError]=useState("");const load=async()=>{const r=await fetch('/api/admin/gallery'),b=await r.json();if(r.ok)setRows(b.data||[]);else setError(b.error||"No se pudo cargar la galería.")};useEffect(()=>{void load()},[]);
async function upload(file:File){setUploading(true);const form=new FormData();form.set('file',file);form.set('category','gallery');form.set('idHint',draft.title||'trabajo-dcl');const r=await fetch('/api/admin/upload',{method:'POST',body:form}),b=await r.json();setUploading(false);if(!r.ok)return setError(b.error||"No se pudo subir la imagen.");setDraft(old=>({...old,imageUrl:b.publicUrl}))}
async function create(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/gallery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)}),b=await r.json();if(!r.ok)return setError(b.error||"No se pudo agregar.");setDraft({imageUrl:"",title:"",caption:"",itemType:"installation",sortOrder:rows.length+1});void load()}
async function update(row:Row){const r=await fetch('/api/admin/gallery',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:row.id,title:row.title,caption:row.caption,itemType:row.item_type,active:row.active,sortOrder:row.sort_order})});if(!r.ok)setError("No se pudo guardar el cambio.");else void load()}
async function remove(id:string){if(!window.confirm('¿Eliminar esta foto de la galería?'))return;await fetch('/api/admin/gallery',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});void load()}
return <div className="space-y-6"><header><h1 className="text-3xl font-black">Galería — DCL en acción</h1><p className="mt-2 text-sm text-zinc-400">Publicá entregas e instalaciones sin incluir nombres, patentes ni otros datos personales.</p></header>{error&&<p className="rounded-xl bg-red-500/10 p-3 text-red-200">{error}</p>}<form onSubmit={create} className="grid gap-3 rounded-2xl border border-white/10 p-4 sm:grid-cols-2"><label className="rounded-xl border border-dashed border-white/20 p-4 text-sm"><span>{uploading?'Subiendo…':draft.imageUrl?'Imagen lista':'Elegir imagen'}</span><input type="file" accept="image/*" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Título" className="rounded-xl bg-zinc-900 p-3"/><input value={draft.caption} onChange={e=>setDraft({...draft,caption:e.target.value})} placeholder="Texto corto (sin datos personales)" className="rounded-xl bg-zinc-900 p-3 sm:col-span-2"/><select value={draft.itemType} onChange={e=>setDraft({...draft,itemType:e.target.value})} className="rounded-xl bg-zinc-900 p-3"><option value="installation">Instalación</option><option value="delivery">Entrega</option><option value="customer">Cliente</option><option value="other">Otro</option></select><button disabled={!draft.imageUrl||uploading} className="rounded-xl bg-red-600 p-3 font-bold disabled:opacity-40">Agregar a la galería</button></form><div className="grid gap-4 md:grid-cols-2">{rows.map(row=><article key={row.id} className="rounded-2xl border border-white/10 p-4"><img src={row.image_url} alt="" loading="lazy" className="aspect-video w-full rounded-xl object-cover"/><input value={row.title||""} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,title:e.target.value}:x))} className="mt-3 w-full rounded-xl bg-zinc-900 p-3"/><textarea value={row.caption||""} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,caption:e.target.value}:x))} className="mt-2 w-full rounded-xl bg-zinc-900 p-3"/><div className="mt-3 flex flex-wrap items-center gap-3"><label><input type="checkbox" checked={row.active} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,active:e.target.checked}:x))}/> Visible</label><input type="number" aria-label="Orden" value={row.sort_order} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,sort_order:Number(e.target.value)}:x))} className="w-20 rounded-lg bg-zinc-900 p-2"/><button onClick={()=>void update(row)} className="rounded-full border border-white/20 px-4 py-2 text-xs">Guardar</button><button onClick={()=>void remove(row.id)} className="text-xs text-red-300">Eliminar</button></div></article>)}</div></div>}
