/* eslint-disable @next/next/no-img-element, react-hooks/set-state-in-effect */
"use client";

import { useEffect, useState } from "react";

type Row = { id:string; name:string; genre:string; stream_url:string; cover_url:string|null; description:string; active:boolean; featured:boolean; sort_order:number };
type Draft = { name:string; genre:string; streamUrl:string; coverUrl:string; description:string; active:boolean; featured:boolean; sortOrder:number };
const emptyDraft:Draft={name:"",genre:"",streamUrl:"",coverUrl:"",description:"",active:true,featured:false,sortOrder:0};
const field="rounded-xl border border-white/10 bg-zinc-900 p-3 text-white outline-none focus:border-red-500/60";

export function MusicManager(){
  const[rows,setRows]=useState<Row[]>([]),[draft,setDraft]=useState<Draft>(emptyDraft),[error,setError]=useState(""),[notice,setNotice]=useState(""),[uploading,setUploading]=useState(false);
  async function load(){const r=await fetch("/api/admin/music"),b=await r.json();if(r.ok)setRows(b.data??[]);else setError(b.error||"No se pudieron cargar las emisoras.")}
  useEffect(()=>{void load()},[]);
  async function upload(file:File,rowId?:string){setUploading(true);setError("");const form=new FormData();form.set("file",file);form.set("category","music");form.set("idHint",rowId||draft.name||"dcl-music");const r=await fetch("/api/admin/upload",{method:"POST",body:form}),b=await r.json();setUploading(false);if(!r.ok)return setError(b.error||"No se pudo subir la portada.");if(rowId)setRows(all=>all.map(row=>row.id===rowId?{...row,cover_url:b.publicUrl}:row));else setDraft(current=>({...current,coverUrl:b.publicUrl}))}
  async function create(e:React.FormEvent){e.preventDefault();setError("");setNotice("");const r=await fetch("/api/admin/music",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)}),b=await r.json();if(!r.ok)return setError(b.error||"No se pudo crear la emisora.");setDraft({...emptyDraft,sortOrder:rows.length+1});setNotice("Emisora agregada.");await load()}
  async function update(row:Row){setError("");setNotice("");const r=await fetch("/api/admin/music",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,name:row.name,genre:row.genre,streamUrl:row.stream_url,coverUrl:row.cover_url||"",description:row.description,active:row.active,featured:row.featured,sortOrder:row.sort_order})}),b=await r.json();if(!r.ok)return setError(b.error||"No se pudo guardar la emisora.");setNotice(`Se guardó “${row.name}”.`);await load()}
  async function remove(row:Row){if(!window.confirm(`¿Eliminar “${row.name}”? Si querés conservarla, desactivala en su lugar.`))return;const r=await fetch("/api/admin/music",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})}),b=await r.json();if(!r.ok)return setError(b.error||"No se pudo eliminar la emisora.");setNotice("Emisora eliminada.");await load()}
  return <div className="space-y-6"><header><span className="text-xs font-bold uppercase tracking-[.2em] text-red-400">Sitio y configuración</span><h1 className="mt-2 text-3xl font-black">DCL Music</h1><p className="mt-2 max-w-2xl text-sm text-zinc-400">Administrá las emisoras del reproductor público. Usá la URL HTTPS directa del stream, no M3U ni PLS.</p></header>{error&&<p className="rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-200">{notice}</p>}
  <form onSubmit={create} className="grid gap-3 rounded-2xl border border-white/10 bg-zinc-950/70 p-4 sm:grid-cols-2"><h2 className="text-lg font-black sm:col-span-2">Nueva emisora</h2><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Nombre" className={field}/><input value={draft.genre} onChange={e=>setDraft({...draft,genre:e.target.value})} placeholder="Género / estilo" className={field}/><input required type="url" value={draft.streamUrl} onChange={e=>setDraft({...draft,streamUrl:e.target.value})} placeholder="https://stream..." className={`${field} sm:col-span-2`}/><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Descripción corta" className={`${field} sm:col-span-2`}/><input value={draft.coverUrl} onChange={e=>setDraft({...draft,coverUrl:e.target.value})} placeholder="URL de portada (opcional)" className={field}/><label className={`${field} cursor-pointer text-sm`}>{uploading?"Subiendo…":"Subir portada"}<input type="file" accept="image/*" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label><input type="number" value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})} aria-label="Orden" className={field}/><div className="flex items-center gap-5 rounded-xl border border-white/10 p-3 text-sm"><label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Activa</label><label><input type="checkbox" checked={draft.featured} onChange={e=>setDraft({...draft,featured:e.target.checked})}/> Destacada</label></div><button disabled={uploading} className="rounded-xl bg-red-600 p-3 text-sm font-bold disabled:opacity-40 sm:col-span-2">Agregar emisora</button></form>
  <div className="grid gap-4 xl:grid-cols-2">{rows.map(row=><article key={row.id} className="rounded-2xl border border-white/10 bg-zinc-950/70 p-4"><div className="flex gap-4">{row.cover_url?<img src={row.cover_url} alt="" className="h-20 w-20 rounded-xl object-cover"/>:<div className="grid h-20 w-20 shrink-0 place-items-center rounded-xl bg-red-600/10 text-2xl text-red-300">♪</div>}<div className="min-w-0 flex-1"><input value={row.name} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,name:e.target.value}:x))} className={`${field} w-full font-bold`}/><input value={row.genre} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,genre:e.target.value}:x))} placeholder="Género" className={`${field} mt-2 w-full`}/></div></div><input value={row.stream_url} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,stream_url:e.target.value}:x))} className={`${field} mt-3 w-full`}/><textarea value={row.description} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,description:e.target.value}:x))} className={`${field} mt-3 w-full`}/><div className="mt-3 flex flex-wrap items-center gap-3 text-sm"><label><input type="checkbox" checked={row.active} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,active:e.target.checked}:x))}/> Activa</label><label><input type="checkbox" checked={row.featured} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,featured:e.target.checked}:x))}/> Destacada</label><input type="number" aria-label="Orden" value={row.sort_order} onChange={e=>setRows(all=>all.map(x=>x.id===row.id?{...x,sort_order:Number(e.target.value)}:x))} className="w-20 rounded-lg bg-zinc-900 p-2"/><label className="cursor-pointer rounded-full border border-white/15 px-3 py-2 text-xs">Cambiar portada<input type="file" accept="image/*" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,row.id)}}/></label></div><div className="mt-4 flex gap-3"><button onClick={()=>void update(row)} className="rounded-full bg-red-600 px-4 py-2 text-xs font-bold">Guardar</button><button onClick={()=>void remove(row)} className="px-3 py-2 text-xs text-red-300">Eliminar</button></div></article>)}</div></div>
}
